name = "XKCD"
uuid = "4bc7fa8b-4ef2-4643-8c8b-cef036f85839"
authors = ["joshday <emailjoshday@gmail.com>"]
version = "0.2.0"

[deps]
DefaultApplication = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
DefaultApplicatoin = "0.1"
HTTP = "0.8"
JSON3 = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
